print('Hello China')
print("Hello World")
print("Hello 'Japan'")
print('Hello "India"')
print('-----------------------------')
print('\n')

print('hi,I\'m Alice')
print("hi,I'm 'Rohan'")
print("yellow\'car\'")
print('Hi,it is "Switzerland"')
print('-----')

print('milkeyway\ngalaxy')
print("Tokyo\n'University")
print('"Osaka"\n"institute"')
print("---------------")
print('\n')

print('name:\t"Saurabh"')
print("village;\t'Harnawa'")
print("age;\t16")
print('course;\t"Operating System"')
print('----------------')
print("\n")

print('Hello\bWorld')
print("mango \bjuice")
print('---------------------')
print('\n')

print('\\')
print(r'\\')
print("\\"+"\\")
print(r"\\"+"\\")
print('\\')
print('\\\\\\')
print('------------------')
print('\n')